# Generated by Django 4.1.6 on 2023-02-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('In_process', 'In_process'), ('Successful', 'Successful')], default=0, max_length=250),
        ),
    ]
